Fix dry contacts status for EMP02
42ity/nut pull request #127
Opened 2021-02-01 13:43 UTC by eric3873

2021-02-01 13:51 UTC, boricj submitted a review, later dismissed

2021-02-15 13:10 UTC, aquette requested changes
please bump the driver version to ensure that we see (from the user PoV) the modification.thx

2021-02-15 13:45 UTC, boricj approved these changes

2021-02-16 08:45 UTC, jimklimov approved these changes
I wonder why this changeset differs from #126, at least WRT `#if WITH_SNMP_LKP_FUN` blocks... I suppose builds with newer compilers and harsher settings would fail due to explicitly-uninitialized fields; with older compilers and softer settings they would not but behavior is generally undefined.

2021-03-05 09:02 UTC, jimklimov commented
Confirmed on call today that we should still wait for a verdict from validation against HW.

2021-04-19 14:50 UTC, closed without merging